// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa8gn0RBkuXzKM9MQ08DPwPxPwYFy48Vk',
    appId: '1:605208683319:web:ec9124de4d5e0af59670b2',
    messagingSenderId: '605208683319',
    projectId: 'pmgp-26c3b',
    authDomain: 'pmgp-26c3b.firebaseapp.com',
    storageBucket: 'pmgp-26c3b.appspot.com',
    measurementId: 'G-7EYQDWWJ99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0mmO6HkNwF84el2TCaEj54S5kBysZEpM',
    appId: '1:605208683319:android:ae3094d77bb55c8f9670b2',
    messagingSenderId: '605208683319',
    projectId: 'pmgp-26c3b',
    storageBucket: 'pmgp-26c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMs_JfU41ErTZBPvPua66VsLo1WuhTwOk',
    appId: '1:605208683319:ios:7670bbe62092a2c99670b2',
    messagingSenderId: '605208683319',
    projectId: 'pmgp-26c3b',
    storageBucket: 'pmgp-26c3b.appspot.com',
    androidClientId: '605208683319-f40f3kjk4a2q3lbdom7ecpav7jfmfn3u.apps.googleusercontent.com',
    iosClientId: '605208683319-vlpq3mo8jsvev1saeqo1b3lgd544u1db.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashbord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMs_JfU41ErTZBPvPua66VsLo1WuhTwOk',
    appId: '1:605208683319:ios:7670bbe62092a2c99670b2',
    messagingSenderId: '605208683319',
    projectId: 'pmgp-26c3b',
    storageBucket: 'pmgp-26c3b.appspot.com',
    androidClientId: '605208683319-f40f3kjk4a2q3lbdom7ecpav7jfmfn3u.apps.googleusercontent.com',
    iosClientId: '605208683319-vlpq3mo8jsvev1saeqo1b3lgd544u1db.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashbord',
  );
}
